# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-4-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Insco.FaForever
PackageVersion: 0.0.1.23
PackageLocale: zh-CN
Publisher: kjxbyz
PublisherUrl: https://chenyifaer.com/faforever
PublisherSupportUrl: https://github.com/cyf/faforever/discussions
PrivacyUrl: https://www.chenyifaer.com/faforever/zh/legal/privacy/
Author: kjxbyz
PackageName: FaForever
PackageUrl: https://chenyifaer.com/faforever
License: MIT
LicenseUrl: https://raw.githubusercontent.com/cyf/faforever/main/LICENSE
Copyright: Copyright (c) 2023 cyf
# CopyrightUrl:
ShortDescription: A third-party music player that replaces Synology DS Audio client.
Description: A third-party music player that replaces Synology DS Audio client.
Tags:
- audio
- music
ReleaseNotes: 'chore: v0.0.1.23'
ReleaseNotesUrl: https://raw.githubusercontent.com/cyf/faforever/main/CHANGELOG.md
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: locale
ManifestVersion: 1.6.0
